# Interactive component

In this section, we will use D3 to construct interactive and animated line chart to show the percentage of each level of education attainment over the total population. In the below interactive line chart, readers are free to plot the line chart of the change of percentage from 2015 to 2019 of their chosen levels of education attainment. There are five levels to choose:Less than High School, High School Graduate, Some College or Associate Degree, Bachelor Degree, and Graduate or professional Degree. Each line are plotted from 2015 to 2019 animatedly to help the readers better detect the trend of percentage for each education level.


<script src="https://d3js.org/d3.v6.js"></script>  <!-- link to D3 library -->


  <h2>Interactive Line Chart for Education Attainment from 2015 to 2019</h2>
  <input type="checkbox" id="lessHS" value="lessHS">
  <label for="vehicle1"> Less than High School</label><br>
  <input type="checkbox" id="HS" value="HS">
  <label for="vehicle2"> High School Graduate</label><br>
  <input type="checkbox" id ="associate" value="associate">
  <label for="vehicle3"> Some College or Associate Degree </label><br>
  <input type="checkbox" id="bachelor" value="bachelor">
  <label for="vehicle3"> Bachelor's Degree</label><br>
  <input type="checkbox" id="advanced" value="advanced">
  <label for="vehicle3"> Graduate or Professional Degree</label><br>




<div id= "plot"></div>

<script>
  var w = 750;
  var h = 550;
  var margin = {top: 25, right: 250, bottom: 25,left: 30};
  var innerWidth = w - margin.left - margin.right;
  var innerHeight = h - margin.top - margin.bottom;
  var lessHS = [[0.1285585,2015], [0.1254705,2016], [0.1201455,2017], [0.1167068,2018], [0.1139115,2019]];
  var HS = [[0.2756469,2015], [0.2717640,2016], [0.2713289,2017], [0.2686960,2018], [0.2689317,2019]];
  var associate = [[0.2897543,2015], [0.2899876,2016], [0.2886797,2017], [0.2885941,2018], [0.2858890,2019]];
  var bachelor = [[0.1901267,2015], [0.1933507,2016], [0.1969944,2017], [0.1998540,2018], [0.2033382,2019]];
  var advanced = [[0.1159136,2015], [0.1194270,2016], [0.1228514,2017], [0.1261490,2018], [0.1279295,2019]];
  
  var xScale = d3.scaleBand()
      .domain(d3.range(2015,2020))
      .range([0, innerWidth]);
      
  var yScale = d3.scaleLinear()
      .domain([0.1, 0.3])
      .range([innerHeight, 0])

  var xAxis = d3.axisBottom()
      .scale(xScale);

  var yAxis = d3.axisLeft()
      .scale(yScale);
  var svg =d3.select("div#plot")
      .append("svg")
      .attr("width",w)
      .attr("height",h);
      
  var mylinegen = d3.line()
  
  mylinegen
    .x(d => xScale(d[1])+50)
    .y(d => yScale(d[0]));
 
  svg.append("g")
      .attr("class", "xAxis")
      .attr("transform", `translate (${margin.left}, ${h - margin.bottom})`)
      .call(xAxis);

  svg.append("g")
      .attr("class", "yAxis")
      .attr("transform", `translate (${margin.left}, ${margin.top})`)
      .call(yAxis);
  svg.append("text")
      .attr("x","10")
      .attr("y","18")
      .text("Proportion")
      .style("font-size", "12px");
  svg.append("text")
      .attr("x","505")
      .attr("y","530")
      .text("Year")
      .style("font-size", "12px");
      
	d3.select("#lessHS").on("change",update1);
	d3.select("#HS").on("change",update2);
	d3.select("#associate").on("change",update3);
	d3.select("#bachelor").on("change",update4);
	d3.select("#advanced").on("change",update5);
  
  function drawline(data,ID,color,svg_){
  	var mypath = mylinegen(data);
    svg_.append("g")
				.attr("id",ID)
        .attr("transform", `translate (${margin.left}, ${margin.top})`)
        .append("path")
        .attr("d", mypath)
        .attr("fill", "none").attr("stroke", color)
        .attr("stroke-width", "3")
        .attr("stroke-dasharray","385 385")
        .attr("stroke-dashoffset", "385")
        .transition()
        .duration(1500)
        .attr('stroke-dashoffset', 0);
  }
  
  function add_legend(text, color,y,ID){
    svg.append("g")
        .attr("id", ID)
        .append("rect")
        .attr("x","500")
        .attr("y",y)
        .attr("width","20")
        .attr("height","20")
        .attr("fill", color);
    svg.append("text")
        .attr("id",ID)
        .attr("x","525")
        .attr("y", y+20)
        .text(text);
  }
	function update1(){
		  if(d3.select("input#lessHS").property("checked")){
		    drawline(lessHS,"lesshs","#c7f3ff",svg);
		    add_legend("Less Than High School","#c7f3ff",25,"legend1");
		  }else{
		    svg.select("#lesshs").remove();
		    svg.select("#legend1").remove();
		    svg.select("text#legend1").remove();
		  }
	};
	
	function update2(){
	  if(d3.select("input#HS").property("checked")){
		    drawline(HS,"hs","#b3cde3",svg);
		    add_legend("High School Graduate","#b3cde3",50,"legend2");
		}else{
		    svg.select("#hs").remove();
		    svg.select("#legend2").remove();
		    svg.select("text#legend2").remove();
		}
	};
	function update3(){
	  if(d3.select("input#associate").property("checked")){
		    drawline(associate,"associated","#6473bf",svg);
		    add_legend("Some College Degree","#6473bf",75,"legend3");

		}else{
        svg.select("#associated").remove();
		    svg.select("#legend3").remove();
		    svg.select("text#legend3").remove();
		}
	};
	function update4(){
	  if(d3.select("input#bachelor").property("checked")){
		    drawline(bachelor,"bachelors","#9b6cb9",svg);
		    add_legend("Bachelor's Degree","#9b6cb9",100,"legend4");

		}else{
        svg.select("#bachelors").remove();
		    svg.select("#legend4").remove();
		    svg.select("text#legend4").remove();
		}
	};
	function update5(){
	  if(d3.select("input#advanced").property("checked")){
		    drawline(advanced,"advance","#810f7c",svg);
		    add_legend("Graduate/Professional Degree","#810f7c",125,"legend5");

		}else{
        svg.select("#advance").remove();
        svg.select("#legend5").remove();
		    svg.select("text#legend5").remove();
		
		}
	};

</script>

From the above line chart, we can observe an overall improvement of education attainment from 2015 to 2019 in the United States. Firstly, the line representing percentage of people who do not go to high school over the total population clearly goes down. Besides, even though the line for people with high school graduate degree the line for people with some college or associate degree look relatively flat, there's still a trend of decreasing from 2015 to 2019. Moreover, there are relatively large increases for the percentages people who obtain bachelor degree or higher. Therefore, there's a overall improvement of education attainment from 2015 tp 2019 in the United States. 

