# Conclustion

Although our data sets gained from census official website provide us with reliable and summarized data, they also create a limitation for our data visualization. Since each data set from census contains essential information on the focused topic, they normally do not have a large number of variables in each data set. in order to fully explore our topic, we need to browse multiple data sets and collect the relevant information. However, because each data set is specific to one topic, the consistency of data among different data sets is hard to determined. This characteristic of our data source limits the amount of data with consistency and the interaction among multiple variables for our project. 

In the future, if we could gain more variables with corresponding counts related to education attainment, we could explore the current stage of education attainment in the United States further more. Besides, after observing the contrast between the proportion of female attaining higher education degrees and the median earning of female population in the United States, we would like to investigate further on the current education attainment stage of female and their median earnings with the interaction with more variables and/or factors. 

In general, even though the uniqueness of our source's data type creates some limits and difficulties in the visualization process, it also gives us the chance of transforming those data into the form we want and applying the plotting techniques on count data. Moreover, the time-consuming procedure of exploring the data set that we are interested in and has reliability makes us realize the importance of data source in data visualization. Having an accurate and reliable data set is the key and cornerstone of data visualization and further processes. 

