--- 
title: "Education Attainment in the US"
author: "Yifei Chen and Zujun Peng"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
--- 
title: "Education Attainment in the US"
author: "Yifei Chen and Zujun Peng"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


<!--chapter:end:index.Rmd-->

# Data Sources


<!--chapter:end:02-data.Rmd-->

# Data Cleaning

```{r}
library(tidyverse)
library(dplyr)
```


```{r}
birth <- read.csv("./data/births.csv", na.strings = "N/A")

```

```{r}
birth <- birth %>% pivot_longer(cols =1:20 ,names_to = c("give_birth","marriage","education"),
    names_sep = "_",
    values_to = "estimate")
```

```{r}
birth[,1:20] <- as.numeric(birth[,1:20])
```

```{r}
race <- read.csv("./data/race.csv", na.strings = "N/A")

```

```{r}
race$Other_High.school.graduate.or.higher<-race$American.Indian.or.Alaska.Native.alone_High.school.graduate.or.higher+race$Native.Hawaiian.and.Other.Pacific.Islander.alone_High.school.graduate.or.higher+race$Some.other.race.alone_High.school.graduate.or.higher + race$Two.or.more.races_High.school.graduate.or.higher

race$Other_Bachelors.s.degree.or.higher <- race$American.Indian.or.Alaska.Native.alone_Bachelor.s.degree.or.higher + race$Native.Hawaiian.and.Other.Pacific.Islander.alone_Bachelor.s.degree.or.higher + race$Some.other.race.alone_Bachelor.s.degree.or.higher + race$Two.or.more.races_Bachelor.s.degree.or.higher

#Then drop columns!
```

```{r}
race<- race %>% pivot_longer(cols = !Gender ,names_to = c("Race","education"),
    names_sep = "_",
    values_to = "estimate")
```

```{r}
race
```



<!--chapter:end:03-cleaning.Rmd-->

# Missing values

<!--chapter:end:04-missing.Rmd-->

# Results

<!--chapter:end:05-results.Rmd-->

# Interactive component

<!--chapter:end:06-interactive.Rmd-->

# Conclustion

<!--chapter:end:07-conclusion.Rmd-->

